### ISSUE TITLE
Cmder

### ISSUE THREAD

**Issue by Cristopher-Duarte** [albertopinedaorozco/ejemploteam#7]
## ¿ Como puedo replicar el problema ?

No puedo subir las cosas a git por cmander

![descarga](https://user-images.githubusercontent.com/51889560/61745682-af88fe80-ad5f-11e9-802c-4b16b5cd794c.png)

**Comment by albertopinedaorozco** [comment]
Luego de realizar los cambios en la nueva branch, entonces debes hacer un push al repositorio remoto
