### ISSUE TITLE
falla en la interfaz

### ISSUE THREAD

**Issue by Alejandro-Gutierrez** [albertopinedaorozco/ejemploteam#8]
## ¿ Como puedo replicar el problema ?

cuando se presiona el botón aceptar se produce un error en el header

**Comment by Federico2202** [comment]
No entiendo muy bien tu error, Por favor explicalo mejor.

**Comment by albertopinedaorozco** [comment]
ok

**Comment by Federico2202** [comment]
Ya lo resolvi
