### ISSUE TITLE
 auyda

### ISSUE THREAD

**Issue by danielortizarenas1007698114** [albertopinedaorozco/ejemploteam#9]
## ¿ Como puedo replicar el problema ?

cuando el ciclo for tiene punto y coma no sirve ; ?

## ¿ En que versión ocurre ?
en cualquier lenguaje de programación que use krico

**Comment by TheDarkMal** [comment]
un gran poder conlleva una  gran responsabilidad

**Comment by albertopinedaorozco** [comment]
ok
